#!/bin/bash
echo $PROJECT_NAME
echo $USER_NAME
echo $USER_PASSWORD

# SQL 스크립트 실행
mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<EOF
CREATE USER IF NOT EXISTS '$USER_NAME'@'%' IDENTIFIED BY '$USER_PASSWORD';  # 사용자 생성
GRANT ALL PRIVILEGES ON *.* TO '$USER_NAME'@'%' WITH GRANT OPTION;  # 권한 부여
FLUSH PRIVILEGES;
EOF
