services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_NAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${USER_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: "peopledb"

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      USER_NAME: ${USER_NAME:-admin}
      USER_PASSWORD: ${USER_PASSWORD:-admin}

    volumes:
      - ./data/redis:/data
      - ./config/redis:/usr/local/etc/redis
    command: ["sh", "/usr/local/etc/redis/start.sh"]
