services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: "123123"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "123123"
      TZ: 'Z'

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "user"
      MONGO_INITDB_ROOT_PASSWORD: "123123"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
