## Filebeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/filebeat.docker.yml
#

name: filebeat

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /logs/**/*.log

processors:
  - add_cloud_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    hosts: [http://elasticsearch:9200]
    username: beats_system
    password: ${BEATS_SYSTEM_PASSWORD}

#output.elasticsearch:
#  hosts: [http://elasticsearch:9200]
#  username: filebeat_internal
#  password: ${FILEBEAT_INTERNAL_PASSWORD}

output.logstash:
  hosts: ['logstash:5044']

## HTTP endpoint for health checking
## https://www.elastic.co/docs/reference/beats/filebeat/http-endpoint
#

http:
  enabled: true
  host: 0.0.0.0
